"use client";

import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import {
  Clipboard, ArrowRight, Download, Trash2, AlertTriangle,
  CheckCircle, ChevronDown, ChevronUp, Clock, Pill, ShieldAlert, ShieldCheck,
} from 'lucide-react';
import { getChecks, deleteCheck, subscribeToHistory, MedCheck } from '@/lib/historyService';

// ── helpers ────────────────────────────────────────────────────────────────

function formatDate(ts: number) {
  return new Intl.DateTimeFormat('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(new Date(ts));
}

function riskBadge(level: MedCheck['risk_level']) {
  switch (level) {
    case 'high':
      return { label: 'High Risk', cls: 'bg-rose-100 text-rose-700 border-rose-200', icon: ShieldAlert };
    case 'moderate':
      return { label: 'Moderate Risk', cls: 'bg-amber-100 text-amber-700 border-amber-200', icon: AlertTriangle };
    case 'low':
      return { label: 'Low Risk', cls: 'bg-emerald-100 text-emerald-700 border-emerald-200', icon: CheckCircle };
    default:
      return { label: 'Unknown', cls: 'bg-slate-100 text-slate-600 border-slate-200', icon: ShieldCheck };
  }
}

// ── PDF generation for a single saved check ────────────────────────────────

async function downloadCheckPDF(check: MedCheck) {
  try {
    const html2pdf = (await import('html2pdf.js')).default;

    const medRows = check.medications
      .map((m) => `<tr><td style="padding:6px 8px;border-bottom:1px solid #e2e8f0">${m.name}</td><td style="padding:6px 8px;border-bottom:1px solid #e2e8f0">${m.dose}</td><td style="padding:6px 8px;border-bottom:1px solid #e2e8f0">${m.specialist}</td></tr>`)
      .join('');

    const html = `
      <div style="font-family:Georgia,serif;color:#1e293b;padding:32px;max-width:780px;margin:auto">
        <div style="display:flex;align-items:center;gap:12px;margin-bottom:24px;padding-bottom:16px;border-bottom:2px solid #0d9488">
          <div style="width:40px;height:40px;background:#0d9488;border-radius:50%;display:flex;align-items:center;justify-content:center">
            <span style="color:white;font-size:18px">✦</span>
          </div>
          <div>
            <h1 style="margin:0;font-size:22px;color:#0d9488">MedTrack Interaction Report</h1>
            <p style="margin:0;font-size:12px;color:#64748b">${formatDate(check.timestamp)}</p>
          </div>
        </div>

        <h2 style="font-size:16px;margin-bottom:8px">Medications Analyzed (${check.analyzed_count})</h2>
        <table style="width:100%;border-collapse:collapse;margin-bottom:24px;font-size:14px">
          <thead>
            <tr style="background:#f8fafc">
              <th style="text-align:left;padding:8px;border-bottom:2px solid #e2e8f0">Drug</th>
              <th style="text-align:left;padding:8px;border-bottom:2px solid #e2e8f0">Dose</th>
              <th style="text-align:left;padding:8px;border-bottom:2px solid #e2e8f0">Specialist</th>
            </tr>
          </thead>
          <tbody>${medRows}</tbody>
        </table>

        <div style="background:#fff1f2;padding:16px;border-radius:12px;border:1px solid #fecdd3;margin-bottom:16px">
          <h3 style="margin:0 0 6px;font-size:13px;color:#be123c;text-transform:uppercase;letter-spacing:1px">Short Analysis</h3>
          <p style="margin:0;font-size:14px;color:#9f1239">${check.short_analysis}</p>
        </div>

        ${check.medium_analysis ? `
        <div style="background:#fffbeb;padding:16px;border-radius:12px;border:1px solid #fde68a;margin-bottom:16px">
          <h3 style="margin:0 0 6px;font-size:13px;color:#92400e;text-transform:uppercase;letter-spacing:1px">Interaction Context</h3>
          <p style="margin:0;font-size:14px;color:#78350f">${check.medium_analysis}</p>
        </div>` : ''}

        ${check.detailed_report ? `
        <div style="background:#f8fafc;padding:16px;border-radius:12px;border:1px solid #e2e8f0;margin-bottom:24px">
          <h3 style="margin:0 0 10px;font-size:13px;color:#1e293b;text-transform:uppercase;letter-spacing:1px">Detailed Clinical Report</h3>
          <pre style="margin:0;font-size:13px;color:#334155;white-space:pre-wrap;font-family:Georgia,serif">${check.detailed_report}</pre>
        </div>` : ''}

        <p style="font-size:11px;color:#94a3b8;text-align:center;border-top:1px solid #e2e8f0;padding-top:16px">
          Generated by MedTrack · Clinical decision support only · Always verify with a licensed pharmacist.
        </p>
      </div>
    `;

    const el = document.createElement('div');
    el.innerHTML = html;
    document.body.appendChild(el);

    const opt: any = {
      margin: 0.4,
      filename: `MedTrack-${new Date(check.timestamp).toISOString().slice(0, 10)}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' },
    };

    await html2pdf().set(opt).from(el).save();
    document.body.removeChild(el);
  } catch (e) {
    console.error('PDF error', e);
  }
}

// ── Single check card ──────────────────────────────────────────────────────

function CheckCard({ check, onDelete }: { check: MedCheck; onDelete: (id: string) => void }) {
  const [expanded, setExpanded] = useState(false);
  const badge = riskBadge(check.risk_level);
  const BadgeIcon = badge.icon;

  return (
    <div className="bg-white rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-shadow">
      {/* Header row */}
      <div className="p-5 flex items-start gap-4">
        <div className={`shrink-0 w-10 h-10 rounded-full flex items-center justify-center border ${badge.cls}`}>
          <BadgeIcon className="w-5 h-5" />
        </div>

        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2 mb-1">
            <span className={`text-xs font-bold px-2 py-0.5 rounded-full border ${badge.cls}`}>
              {badge.label}
            </span>
            <span className="text-xs text-slate-400 flex items-center gap-1">
              <Clock className="w-3 h-3" />{formatDate(check.timestamp)}
            </span>
          </div>

          {/* Drug pills */}
          <div className="flex flex-wrap gap-1.5 mt-2">
            {check.medications.map((m, i) => (
              <span key={i} className="inline-flex items-center gap-1 text-xs bg-slate-100 text-slate-700 px-2 py-0.5 rounded-full">
                <Pill className="w-3 h-3 text-teal-500" />
                {m.name}{m.dose ? ` ${m.dose}` : ''}
              </span>
            ))}
          </div>

          <p className="text-sm text-slate-500 mt-2 line-clamp-2">{check.short_analysis}</p>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2 shrink-0">
          <button
            onClick={() => downloadCheckPDF(check)}
            title="Download PDF"
            className="p-2 text-slate-400 hover:text-[var(--color-brand-teal)] hover:bg-teal-50 rounded-lg transition-colors"
          >
            <Download className="w-4 h-4" />
          </button>
          <button
            onClick={() => onDelete(check.id)}
            title="Delete"
            className="p-2 text-slate-400 hover:text-rose-500 hover:bg-rose-50 rounded-lg transition-colors"
          >
            <Trash2 className="w-4 h-4" />
          </button>
          <button
            onClick={() => setExpanded((v) => !v)}
            className="p-2 text-slate-400 hover:text-slate-700 hover:bg-slate-50 rounded-lg transition-colors"
          >
            {expanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
          </button>
        </div>
      </div>

      {/* Expanded detail */}
      {expanded && (
        <div className="border-t border-slate-100 p-5 space-y-4 animate-[fadeUp_0.3s_ease-out_forwards]">
          {check.medium_analysis && (
            <div className="bg-amber-50 p-4 rounded-xl border border-amber-100">
              <p className="text-xs font-bold text-amber-700 uppercase tracking-wider mb-1">Interaction Context</p>
              <p className="text-sm text-amber-900 leading-relaxed">{check.medium_analysis}</p>
            </div>
          )}
          {check.detailed_report && (
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
              <p className="text-xs font-bold text-slate-600 uppercase tracking-wider mb-2">Detailed Report</p>
              <pre className="text-sm text-slate-700 whitespace-pre-wrap font-serif leading-relaxed">{check.detailed_report}</pre>
            </div>
          )}
          <button
            onClick={() => downloadCheckPDF(check)}
            className="w-full py-2.5 bg-[var(--color-brand-teal)] text-white rounded-xl text-sm font-bold hover:bg-[var(--color-brand-teal-dark)] transition-colors flex items-center justify-center gap-2 hover-lift"
          >
            <Download className="w-4 h-4" /> Download PDF Report
          </button>
        </div>
      )}
    </div>
  );
}

// ── Main page ──────────────────────────────────────────────────────────────

export default function HistoryPage() {
  const [checks, setChecks] = useState<MedCheck[]>([]);
  const [mounted, setMounted] = useState(false);

  const refresh = useCallback(() => setChecks(getChecks()), []);

  useEffect(() => {
    setMounted(true);
    refresh();
    const unsub = subscribeToHistory(setChecks);
    return unsub;
  }, [refresh]);

  const handleDelete = (id: string) => {
    deleteCheck(id);
    // subscribeToHistory will fire & update state automatically
  };

  if (!mounted) return null;

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      {/* Header */}
      <div className="flex items-end justify-between">
        <div>
          <h1 className="text-4xl font-serif text-slate-800 mb-2">Past Medication Checks</h1>
          <p className="text-slate-500 text-lg">Review your history of safety analyses and identified cascades.</p>
        </div>
        {checks.length > 0 && (
          <span className="text-sm font-medium text-slate-500 bg-slate-100 px-3 py-1.5 rounded-full">
            {checks.length} {checks.length === 1 ? 'check' : 'checks'}
          </span>
        )}
      </div>

      {checks.length === 0 ? (
        /* Empty state */
        <div className="bg-white rounded-[2rem] p-16 shadow-sm border-2 border-dashed border-slate-200 flex flex-col items-center justify-center text-center animate-[fadeUp_0.8s_ease-out_forwards]">
          <div className="w-24 h-24 bg-slate-50 rounded-full flex items-center justify-center mb-6 animate-float">
            <Clipboard className="w-12 h-12 text-slate-300" />
          </div>
          <h2 className="text-3xl font-serif text-slate-800 mb-3">No checks yet</h2>
          <p className="text-slate-500 max-w-md mx-auto mb-10 text-lg">
            Your medication check history is currently empty. Run your first full safety report to see results here.
          </p>
          <Link
            href="/dashboard/checker"
            className="px-8 py-4 bg-[var(--color-brand-teal)] text-white rounded-xl font-bold hover:bg-[var(--color-brand-teal-dark)] transition-colors shadow-lg shadow-teal-900/20 hover-lift flex items-center gap-2"
          >
            Check My Medications <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      ) : (
        /* Check list */
        <div className="space-y-4">
          {checks.map((check) => (
            <CheckCard key={check.id} check={check} onDelete={handleDelete} />
          ))}
        </div>
      )}
    </div>
  );
}
