"use client";

import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import {
  Clipboard, ShieldAlert, CheckCircle, Pill, ArrowRight,
  Stethoscope, Clock, Download, AlertTriangle, ShieldCheck,
} from 'lucide-react';
import { auth } from '@/lib/firebase';
import { onAuthStateChanged } from 'firebase/auth';
import {
  getChecks, subscribeToHistory, getStats, MedCheck,
} from '@/lib/historyService';

// ── helpers ────────────────────────────────────────────────────────────────

function formatDate(ts: number) {
  return new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(ts));
}

function riskBadge(level: MedCheck['risk_level']) {
  switch (level) {
    case 'high':     return { label: 'High Risk',    cls: 'bg-rose-100 text-rose-700',    icon: ShieldAlert };
    case 'moderate': return { label: 'Moderate',     cls: 'bg-amber-100 text-amber-700',  icon: AlertTriangle };
    case 'low':      return { label: 'Low Risk',     cls: 'bg-emerald-100 text-emerald-700', icon: CheckCircle };
    default:         return { label: 'Unknown',      cls: 'bg-slate-100 text-slate-600',  icon: ShieldCheck };
  }
}

async function downloadCheckPDF(check: MedCheck) {
  try {
    const html2pdf = (await import('html2pdf.js')).default;
    const medRows = check.medications
      .map((m) => `<tr><td style="padding:6px 8px;border-bottom:1px solid #e2e8f0">${m.name}</td><td style="padding:6px 8px;border-bottom:1px solid #e2e8f0">${m.dose}</td><td style="padding:6px 8px;border-bottom:1px solid #e2e8f0">${m.specialist}</td></tr>`)
      .join('');

    const html = `
      <div style="font-family:Georgia,serif;color:#1e293b;padding:32px;max-width:780px">
        <div style="border-bottom:2px solid #0d9488;margin-bottom:24px;padding-bottom:16px">
          <h1 style="margin:0;font-size:20px;color:#0d9488">MedTrack Interaction Report</h1>
          <p style="margin:4px 0 0;font-size:12px;color:#64748b">${formatDate(check.timestamp)}</p>
        </div>
        <h2 style="font-size:15px;margin-bottom:8px">Medications (${check.analyzed_count})</h2>
        <table style="width:100%;border-collapse:collapse;margin-bottom:20px;font-size:13px">
          <thead><tr style="background:#f8fafc">
            <th style="text-align:left;padding:8px;border-bottom:2px solid #e2e8f0">Drug</th>
            <th style="text-align:left;padding:8px;border-bottom:2px solid #e2e8f0">Dose</th>
            <th style="text-align:left;padding:8px;border-bottom:2px solid #e2e8f0">Specialist</th>
          </tr></thead>
          <tbody>${medRows}</tbody>
        </table>
        <div style="background:#fff1f2;padding:14px;border-radius:10px;border:1px solid #fecdd3;margin-bottom:14px">
          <h3 style="margin:0 0 5px;font-size:12px;color:#be123c;text-transform:uppercase">Short Analysis</h3>
          <p style="margin:0;font-size:13px;color:#9f1239">${check.short_analysis}</p>
        </div>
        ${check.medium_analysis ? `<div style="background:#fffbeb;padding:14px;border-radius:10px;border:1px solid #fde68a;margin-bottom:14px">
          <h3 style="margin:0 0 5px;font-size:12px;color:#92400e;text-transform:uppercase">Context</h3>
          <p style="margin:0;font-size:13px;color:#78350f">${check.medium_analysis}</p></div>` : ''}
        ${check.detailed_report ? `<div style="background:#f8fafc;padding:14px;border-radius:10px;border:1px solid #e2e8f0">
          <h3 style="margin:0 0 8px;font-size:12px;color:#1e293b;text-transform:uppercase">Detailed Report</h3>
          <pre style="margin:0;font-size:12px;color:#334155;white-space:pre-wrap;font-family:Georgia,serif">${check.detailed_report}</pre></div>` : ''}
        <p style="font-size:11px;color:#94a3b8;text-align:center;padding-top:16px;margin-top:16px;border-top:1px solid #e2e8f0">Generated by MedTrack · Clinical decision support only.</p>
      </div>`;

    const el = document.createElement('div');
    el.innerHTML = html;
    document.body.appendChild(el);
    await html2pdf().set({
      margin: 0.4, filename: `MedTrack-${new Date(check.timestamp).toISOString().slice(0, 10)}.pdf`,
      image: { type: 'jpeg', quality: 0.98 }, html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' },
    }).from(el).save();
    document.body.removeChild(el);
  } catch (e) { console.error('PDF error', e); }
}

// ── Main page ──────────────────────────────────────────────────────────────

export default function DashboardHome() {
  const [checks, setChecks] = useState<MedCheck[]>([]);
  const [stats,  setStats]  = useState({ total: 0, alerts: 0, safe: 0, drugs: 0 });
  const [mounted, setMounted] = useState(false);
  const [displayName, setDisplayName] = useState('User');

  const refresh = useCallback(() => {
    setChecks(getChecks().slice(0, 5)); // show 5 most recent on dashboard
    setStats(getStats());
  }, []);

  useEffect(() => {
    setMounted(true);
    refresh();
    const unsub = subscribeToHistory(() => refresh());
    const unsubAuth = onAuthStateChanged(auth, (user) => {
      if (user) {
        setDisplayName(user.displayName || user.email?.split('@')[0] || 'User');
      } else {
        setDisplayName('User');
      }
    });
    return () => {
      unsub();
      unsubAuth();
    };
  }, [refresh]);

  const latestCheck = checks[0] ?? null;

  if (!mounted) return (
    <div className="space-y-8 pb-12 animate-pulse">
      <div className="h-12 w-64 bg-slate-100 rounded-xl" />
    </div>
  );

  return (
    <div className="space-y-8 pb-12">
      {/* Header */}
      <div>
        <h1 className="text-4xl font-serif text-slate-800 mb-2 capitalize">
          Welcome back, {displayName} <span className="inline-block animate-float" style={{ animationDuration: '3s' }}>👋</span>
        </h1>
        <p className="text-slate-500 text-lg">Let&apos;s check if your medications are working safely together.</p>
      </div>

      {/* Banner */}
      <div className="w-full bg-[var(--color-brand-teal)] rounded-3xl p-8 text-white relative overflow-hidden shadow-xl shadow-teal-900/20 hover-lift">
        <div className="absolute top-[-50px] right-[-50px] w-64 h-64 bg-teal-400/20 rounded-full blur-3xl animate-float" />
        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="max-w-xl">
            <h2 className="text-2xl font-serif mb-2">Check your medications now.</h2>
            <p className="text-teal-100 text-lg">Get a full AI safety report in under 30 seconds. Identify hidden cascades before they cause harm.</p>
          </div>
          <Link
            href="/dashboard/checker"
            className="px-8 py-4 bg-white text-[var(--color-brand-teal-dark)] rounded-xl font-bold hover:bg-teal-50 transition-colors shadow-lg shadow-black/10 hover-lift flex items-center justify-center gap-2 whitespace-nowrap"
          >
            Analyze My Medications <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </div>

      {/* Live Stats Grid */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
        {[
          { label: 'Total Checks',   value: stats.total,  icon: Clipboard,   color: 'text-slate-600',   bg: 'bg-slate-100'  },
          { label: 'Alerts Found',   value: stats.alerts, icon: ShieldAlert, color: 'text-rose-600',    bg: 'bg-rose-100'   },
          { label: 'Safe Checks',    value: stats.safe,   icon: CheckCircle, color: 'text-emerald-600', bg: 'bg-emerald-100'},
          { label: 'Drugs Analyzed', value: stats.drugs,  icon: Pill,        color: 'text-indigo-600',  bg: 'bg-indigo-100' },
        ].map((stat, i) => (
          <div key={i} className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 hover-lift flex items-center gap-4">
            <div className={`w-12 h-12 rounded-xl flex items-center justify-center shrink-0 ${stat.bg} ${stat.color}`}>
              <stat.icon className="w-6 h-6" />
            </div>
            <div>
              <div className="text-3xl font-serif text-slate-800">{stat.value}</div>
              <div className="text-sm font-medium text-slate-500">{stat.label}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Bottom split */}
      <div className="grid lg:grid-cols-2 gap-8">

        {/* ── Past Checks (live) ─────────────────────────────────── */}
        <div className="bg-white p-8 rounded-3xl shadow-sm border border-slate-100 hover-lift">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-xl font-serif text-slate-800">Past Medication Checks</h3>
            <Link href="/dashboard/history" className="text-sm font-medium text-[var(--color-brand-teal)] hover:underline flex items-center gap-1">
              View All <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          </div>

          {checks.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 text-center border-2 border-dashed border-slate-200 rounded-2xl">
              <div className="w-16 h-16 bg-slate-50 rounded-full flex items-center justify-center mb-4">
                <Clipboard className="w-8 h-8 text-slate-400" />
              </div>
              <p className="text-slate-600 font-medium mb-1">No checks yet</p>
              <p className="text-sm text-slate-400 max-w-xs">Your medication check history will appear here once you run an analysis.</p>
            </div>
          ) : (
            <div className="space-y-3">
              {checks.map((check) => {
                const badge = riskBadge(check.risk_level);
                const BadgeIcon = badge.icon;
                return (
                  <div key={check.id} className="flex items-center gap-3 p-3.5 rounded-xl border border-slate-100 hover:bg-slate-50 transition-colors group">
                    <div className={`shrink-0 w-8 h-8 rounded-full flex items-center justify-center ${badge.cls}`}>
                      <BadgeIcon className="w-4 h-4" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-slate-800 truncate">
                        {check.medications.map((m) => m.name).join(' · ')}
                      </p>
                      <p className="text-xs text-slate-400 flex items-center gap-1 mt-0.5">
                        <Clock className="w-3 h-3" />{formatDate(check.timestamp)}
                      </p>
                    </div>
                    <button
                      onClick={() => downloadCheckPDF(check)}
                      title="Download PDF"
                      className="p-1.5 text-slate-300 group-hover:text-[var(--color-brand-teal)] hover:bg-teal-50 rounded-lg transition-colors opacity-0 group-hover:opacity-100"
                    >
                      <Download className="w-4 h-4" />
                    </button>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* ── Safety Status (live) ───────────────────────────────── */}
        <div className="bg-[#1A464C] p-8 rounded-3xl shadow-xl shadow-teal-900/10 text-white relative overflow-hidden hover-lift flex flex-col justify-between min-h-[300px]">
          <div className="absolute top-0 right-0 w-full h-full bg-[var(--color-brand-teal)] rounded-full blur-[100px] opacity-20 animate-float" />
          <div className="relative z-10">
            {latestCheck ? (
              <>
                <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full text-sm font-bold tracking-wider mb-6 ${
                  latestCheck.risk_level === 'high'     ? 'bg-rose-400/20 text-rose-200'     :
                  latestCheck.risk_level === 'moderate' ? 'bg-amber-400/20 text-amber-200'   :
                                                          'bg-teal-400/20 text-teal-200'
                }`}>
                  {latestCheck.risk_level === 'high'     ? <ShieldAlert className="w-4 h-4" /> :
                   latestCheck.risk_level === 'moderate' ? <AlertTriangle className="w-4 h-4" /> :
                                                           <CheckCircle className="w-4 h-4" />}
                  {riskBadge(latestCheck.risk_level).label.toUpperCase()}
                </div>
                <h3 className="text-2xl font-serif mb-3 leading-tight">
                  {latestCheck.medications.map((m) => m.name).join(', ')}
                </h3>
                <p className="text-teal-100/80 mb-6 max-w-sm line-clamp-3">{latestCheck.short_analysis}</p>
                <p className="text-xs text-teal-300/60 flex items-center gap-1">
                  <Clock className="w-3 h-3" /> Last check: {formatDate(latestCheck.timestamp)}
                </p>
              </>
            ) : (
              <>
                <div className="inline-flex items-center gap-2 px-3 py-1 bg-teal-400/20 rounded-full text-teal-200 text-sm font-bold tracking-wider mb-6">
                  <CheckCircle className="w-4 h-4" /> ALL CLEAR
                </div>
                <h3 className="text-3xl font-serif mb-4 leading-tight">No checks run yet.</h3>
                <p className="text-teal-100/80 mb-8 max-w-sm text-lg">
                  Run your first medication check to see your personalized safety status and risk profile here.
                </p>
              </>
            )}
          </div>

          <Link
            href="/dashboard/checker"
            className="w-full sm:w-auto self-start px-6 py-3 bg-white text-[var(--color-brand-teal-dark)] rounded-xl font-bold hover:bg-teal-50 transition-colors flex items-center gap-2 hover-lift relative z-10"
          >
            {latestCheck ? 'Run Another Check' : 'Run First Check'} <Stethoscope className="w-5 h-5" />
          </Link>
        </div>

      </div>
    </div>
  );
}
